[project]
name = "streamlined-trace-waterfall"
authors = ["Core Development Team"]
description = "A decentralized trace and licensing platform for digital assets"
telemetry = false
requirements = []
[contracts.waterfall-creator]
path = "contracts/waterfall-creator.clar"
depends_on = []

[contracts.waterfall-licensing]
path = "contracts/waterfall-licensing.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
